# Generated by Django 6.0.3 on 2026-04-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_alert', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sensor Status',
            },
        ),
    ]
