# Generated by Django 6.0.3 on 2026-04-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_alert', '0002_sensorstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='firealert',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='firealert',
            name='stall',
            field=models.CharField(choices=[('stall_1', 'Stall 1'), ('stall_2', 'Stall 2'), ('both', 'Both')], default='stall_1', max_length=10),
        ),
    ]
