# Generated by Django 6.0.3 on 2026-04-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_alert', '0003_firealert_resolved_firealert_stall'),
    ]

    operations = [
        migrations.AddField(
            model_name='firealert',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
