# Generated by Django 6.0.3 on 2026-05-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_alert', '0007_sensorstatus_stalls'),
    ]

    operations = [
        migrations.AddField(
            model_name='firealert',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='firealert',
            name='stall_1_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='firealert',
            name='stall_1_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='firealert',
            name='stall_2_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='firealert',
            name='stall_2_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
